# Generated by Django 2.2.4 on 2019-08-25 13:20

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='created_at')),
                ('citizen_id', models.BigIntegerField()),
                ('town', models.CharField(max_length=2048)),
                ('street', models.CharField(max_length=2048)),
                ('building', models.CharField(max_length=2048)),
                ('apartment', models.BigIntegerField()),
                ('name', models.CharField(max_length=2048)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='created_at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitizenRelative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='created_at')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_citizen_relatives', to='api.Citizen')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_citizen_relatives', to='api.Citizen')),
            ],
            options={
                'unique_together': {('citizen', 'relative')},
            },
        ),
        migrations.AddField(
            model_name='citizen',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DataSet'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='relatives',
            field=models.ManyToManyField(through='api.CitizenRelative', to='api.Citizen'),
        ),
        migrations.AlterUniqueTogether(
            name='citizen',
            unique_together={('data_set', 'citizen_id')},
        ),
    ]
