# Generated by Django 2.2.4 on 2019-08-25 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='api.DataSet'),
        ),
    ]
